name: Build
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        description: Base URL for the site
        required: true
        default: './'
  # Allows you to call this workflow from other workflows
  workflow_call:
    inputs:
      base_url:
        type: string
        description: Base URL for the site
        required: true
        default: './'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          base_url: ${{ github.event.inputs.base_url }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist
