name: Build Storybook
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to call this workflow from other workflows
  workflow_call:

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-storybook
      - name: Upload storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: ./storybook-static
      - name: Upload storybook-docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-docs
          path: ./storybook-docs-static
