name: Deploy to GitHub Pages
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to call this workflow from other workflows
  workflow_call:
    inputs:
      get_built_app_from_artifact:
        type: boolean
        default: false
      get_built_storybook_from_artifact:
        type: boolean
        default: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build app
        if: ${{ !inputs.get_built_app_from_artifact }}
        uses: ./.github/actions/build
        # Note: although the default base URL "./" works on GitHub Pages, if you want to always build the deployed app with base_url explicitly set with the GitHub Page URL, comment out following line, the if condition of this step and the whole "Download built app from Artifact" step
        # with:
        #   base_url: ${{ steps.pages.outputs.base_url }}
      - name: Download built app from Artifact
        if: ${{ inputs.get_built_app_from_artifact }}
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Build Storybook
        if: ${{ !inputs.get_built_storybook_from_artifact }}
        uses: ./.github/actions/build-storybook
      - name: Download built Storybook from Artifact
        if: ${{ inputs.get_built_storybook_from_artifact }}
        uses: actions/download-artifact@v4
        with:
          name: storybook
          path: storybook-static
      - name: Download built Storybook docs from Artifact
        if: ${{ inputs.get_built_storybook_from_artifact }}
        uses: actions/download-artifact@v4
        with:
          name: storybook-docs
          path: storybook-docs-static
      - name: Prepare storybook
        run: |
          mv storybook-static dist/storybook
          mv storybook-docs-static dist/storybook-docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Print deployment URL
        run: echo "Deploying to ${{ steps.pages.outputs.base_url }}"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
