name: Setup Environment
inputs:
  skip_yarn_install:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Cache node_modules
      if: ${{ inputs.skip_yarn_install != 'true' }}
      uses: actions/cache@v4
      env:
        cache-name: node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Install dependencies
      if: ${{ inputs.skip_yarn_install != 'true' }}
      shell: bash
      run: |
        yarn preinstall
        yarn install
