name: Basic Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  # release:
  #   types: [published]
  # schedule:
    # First Sunday of every month
    # See: https://crontab.guru/#0_0_1-7_*_*/7
    # - cron: '0 0 1-7 * */7'  # https://stackoverflow.com/a/73826599
    # # Every Monday
    # - cron: 0 0 * * 1

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages on called workflows
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Lint
        run: |
          yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Typecheck
        run: |
          yarn typecheck

  prepare-test:
    runs-on: ubuntu-latest
    outputs:
      # Expose the package path output from the list-packages step for other jobs to use it.
      package-paths: ${{ steps.list-packages.outputs.package-paths }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          skip_yarn_install: true
      - name: List packages with tests
        uses: zetavg/yarn-workspace-packages-list-action@v0
        id: list-packages
        with:
          # A condition that checks if the package has a "test" script defined in its package.json.
          condition: '[ -f "$package_location/package.json" ] && jq -e ".scripts.test" "$package_location/package.json"'

  test:
    needs: prepare-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare-test.outputs.package-paths) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Test
        run: |
          cd ${{ matrix.package }}
          yarn test

  # test:
  #   strategy:
  #     matrix:
  #       command:
  #         - lint
  #         - typecheck
  #         - test
  #       dir:
  #         - packages/sum
  #         - packages/plus-two
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Environment
  #       uses: ./.github/actions/setup-environment
  #     - name: Run
  #       run: |
  #         cd ${{ matrix.dir }}
  #         yarn g:${{ matrix.command }}
